name: task_pilot_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  q_architecture: ^1.0.0
  pretty_dio_logger: ^1.3.1
  flutter_loggy_dio: ^3.1.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  build_runner: ^2.2.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
